name: Checks

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: echo event
        run: |
          echo "is pull request: ${{ github.event }}"
        if: github.event

      - name: no PR
        run: |
          echo "no pull request"
        if: github.event.pull_request == null
